In [1]:
import os 
os.chdir('../../..')

In [ ]:
import json
import pandas as pd
import plotly.graph_objects as go

from pathlib import Path
from IPython.display import display, Markdown
from plotly.subplots import make_subplots

In [3]:
report_path = Path('results/cluster_reports/consolidated_report.json')
with report_path.open() as f:
    report_data = json.load(f)

cluster_score_keys = sorted(
    k for k in report_data.keys() if k.endswith('cluster_scores.json')
)

isomer_non_euclidean_keys = [
    k for k in cluster_score_keys if 'isomers_non_euclidean' in k
]
isomer_euclidean_keys = [
    k for k in cluster_score_keys if 'isomers_euclidean' in k
]
other_keys = [
    k for k in cluster_score_keys
    if k not in isomer_non_euclidean_keys and k not in isomer_euclidean_keys
]

len(cluster_score_keys)

32

In [4]:
def _title_from_key(key: str) -> str:
    # e.g. non_euclidean/wasserstein_cluster_scores.json -> non_euclidean/wasserstein
    return key.replace('_cluster_scores.json', '')


def _display_scores(keys, section_title=None):
    if section_title:
        display(Markdown(f"# {section_title}"))

    if not keys:
        display(Markdown("No entries found."))
        return

    for key in keys:
        payload = report_data.get(key, {})
        title = _title_from_key(key)

        display(Markdown(f"## {title}"))

        summary = {
            "embedding": payload.get("embedding"),
            "best_k_used": payload.get("best_k_used"),
            "valid_count": payload.get("valid_count"),
            "total_count": payload.get("total_count"),
        }
        display(pd.DataFrame([summary]))

        congruence = payload.get("congruence")
        if isinstance(congruence, dict) and len(congruence) > 0:
            df_congruence = (
                pd.DataFrame(
                    [{"cluster": str(k), "congruence": v} for k, v in congruence.items()]
                )
                .sort_values("cluster")
                .reset_index(drop=True)
            )
            display(Markdown("**Congruence**"))
            display(df_congruence)
        else:
            display(Markdown("**Congruence**: not available"))

        mcs = payload.get("molecular_cluster_score")
        if isinstance(mcs, dict) and len(mcs) > 0:
            if "error" in mcs:
                display(Markdown(f"**Molecular Cluster Score**: {mcs['error']}"))
            else:
                df_mcs = pd.DataFrame([mcs])
                display(Markdown("**Molecular Cluster Score**"))
                display(df_mcs)
        else:
            display(Markdown("**Molecular Cluster Score**: not available"))


_display_scores(isomer_non_euclidean_keys, section_title="Isomer Non-Euclidean")
_display_scores(isomer_euclidean_keys, section_title="Isomer Euclidean")
_display_scores(other_keys, section_title="All Other Cluster Scores")

# Isomer Non-Euclidean

## isomers_non_euclidean/affine_riemann_formula_C7H10O2

            embedding  best_k_used  valid_count  total_count
0  affine_riemann_mds            2          103          103

**Congruence**

  cluster  congruence
0       0    0.540319
1       1    0.472500

**Molecular Cluster Score**

,total_score,structure_score,property_score,category_score,separation_score,structure_class_score
0,0.490385,0.856204,0.085749,0.332946,0.555899,0.887016

## isomers_non_euclidean/euclidean_riemann_formula_C7H10O2

               embedding  best_k_used  valid_count  total_count
0  euclidean_riemann_mds            2          103          103

**Congruence**

  cluster  congruence
0       0    0.494958
1       1    0.410585

**Molecular Cluster Score**

,total_score,structure_score,property_score,category_score,separation_score,structure_class_score
0,0.475101,0.818324,0.084854,0.33133,0.560491,0.876803

## isomers_non_euclidean/grassmann_formula_C7H10O2

       embedding  best_k_used  valid_count  total_count
0  grassmann_mds            7          103          103

**Congruence**

  cluster  congruence
0       0    0.894524
1       1    0.699695
2       2    0.518806
3       3    0.716309
4       4    0.430115
5       5    0.517371
6       6    0.826586

**Molecular Cluster Score**

,total_score,structure_score,property_score,category_score,separation_score,structure_class_score
0,0.522091,0.410087,0.568173,0.584873,0.706296,0.943646

## isomers_non_euclidean/wasserstein_formula_C7H10O2

         embedding  best_k_used  valid_count  total_count
0  wasserstein_mds           14          103          103

**Congruence**

   cluster  congruence
0        0    0.613699
1        1    0.456301
2       10    0.276966
3       11    0.673006
4       12    0.756556
5       13    0.519132
6        2    0.640129
7        3    0.551839
8        4    0.698222
9        5    0.622397
10       6    0.591066
11       7    0.694034
12       8    0.500256
13       9    0.400127

**Molecular Cluster Score**

,total_score,structure_score,property_score,category_score,separation_score,structure_class_score
0,0.288195,0.270123,0.232015,0.456153,0.193104,0.910683

# Isomer Euclidean

## isomers_euclidean/acsf_embedding_formula_C7H10O2

        embedding  best_k_used  valid_count  total_count
0  acsf_embedding            2          103          103

**Congruence**

  cluster  congruence
0       0    0.358625
1       1    0.393662

**Molecular Cluster Score**

,total_score,structure_score,property_score,category_score,separation_score,structure_class_score
0,0.360414,0.627267,0.014602,0.339487,0.372297,0.8

## isomers_euclidean/chemprop_embedding_formula_C7H10O2

            embedding  best_k_used  valid_count  total_count
0  chemprop_embedding            2          103          103

**Congruence**

  cluster  congruence
0       0    0.582805
1       1    0.804475

**Molecular Cluster Score**

,total_score,structure_score,property_score,category_score,separation_score,structure_class_score
0,0.615411,0.794487,0.493124,0.431818,0.633149,0.969697

## isomers_euclidean/morgan_fingerprint_formula_C7H10O2

            embedding  best_k_used  valid_count  total_count
0  morgan_fingerprint           14          103          103

**Congruence**

   cluster  congruence
0        0    0.482081
1        1    0.740577
2       10    0.655141
3       11    0.688696
4       12    0.801033
5       13    0.666667
6        2    0.524935
7        3    0.571301
8        4    0.463150
9        5    0.490076
10       6    0.698016
11       7    0.666667
12       8    0.666667
13       9    0.709034

**Molecular Cluster Score**

,total_score,structure_score,property_score,category_score,separation_score,structure_class_score
0,0.580655,0.537341,0.667396,0.677138,0.300728,0.949405

## isomers_euclidean/selfies_transformer_formula_C7H10O2

             embedding  best_k_used  valid_count  total_count
0  selfies_transformer            2          103          103

**Congruence**

  cluster  congruence
0       0    0.527571
1       1    0.701697

**Molecular Cluster Score**

,total_score,structure_score,property_score,category_score,separation_score,structure_class_score
0,0.377142,0.663219,0.015628,0.355645,0.360367,0.912281

## isomers_euclidean/soap_embedding_formula_C7H10O2

        embedding  best_k_used  valid_count  total_count
0  soap_embedding            2          103          103

**Congruence**

  cluster  congruence
0       0    0.454241
1       1    0.615866

**Molecular Cluster Score**

,total_score,structure_score,property_score,category_score,separation_score,structure_class_score
0,0.426595,0.742396,0.089525,0.305479,0.416832,0.833333

# All Other Cluster Scores

## descriptors_kmeans/acsf_embedding

        embedding  best_k_used  valid_count  total_count
0  acsf_embedding            2         2000         2000

**Congruence**

  cluster  congruence
0       0    0.500695
1       1    0.545999

**Molecular Cluster Score**

,total_score,structure_score,property_score,category_score,separation_score,structure_class_score
0,0.42463,0.713545,0.137568,0.237241,0.504936,0.675578

## descriptors_kmeans/chemprop_embedding

            embedding  best_k_used  valid_count  total_count
0  chemprop_embedding            3         2000         2000

**Congruence**

  cluster  congruence
0       0    0.473743
1       1    0.593254
2       2    0.502101

**Molecular Cluster Score**

,total_score,structure_score,property_score,category_score,separation_score,structure_class_score
0,0.427716,0.709888,0.135616,0.278912,0.472928,0.88164

## descriptors_kmeans/coulomb_matrix

        embedding  best_k_used  valid_count  total_count
0  coulomb_matrix            2         2000         2000

**Congruence**

  cluster  congruence
0       0    0.477147
1       1    0.480236

**Molecular Cluster Score**

,total_score,structure_score,property_score,category_score,separation_score,structure_class_score
0,0.362922,0.68318,0.026191,0.247046,0.32383,0.643686

## descriptors_kmeans/morgan_fingerprint

            embedding  best_k_used  valid_count  total_count
0  morgan_fingerprint            2         2000         2000

**Congruence**

  cluster  congruence
0       0    0.317391
1       1    0.310289

**Molecular Cluster Score**

,total_score,structure_score,property_score,category_score,separation_score,structure_class_score
0,0.297732,0.527881,0.070207,0.252534,0.150107,0.658442

## descriptors_kmeans/selfies_onehot

        embedding  best_k_used  valid_count  total_count
0  selfies_onehot            2         2000         2000

**Congruence**

  cluster  congruence
0       0    0.403631
1       1    0.443713

**Molecular Cluster Score**

,total_score,structure_score,property_score,category_score,separation_score,structure_class_score
0,0.346998,0.571648,0.172662,0.215227,0.234947,0.680847

## descriptors_kmeans/selfies_transformer

             embedding  best_k_used  valid_count  total_count
0  selfies_transformer            2         2000         2000

**Congruence**

  cluster  congruence
0       0    0.500598
1       1    0.477494

**Molecular Cluster Score**

,total_score,structure_score,property_score,category_score,separation_score,structure_class_score
0,0.334914,0.640442,0,0.231672,0.324033,0.738002

## descriptors_kmeans/soap_embedding

        embedding  best_k_used  valid_count  total_count
0  soap_embedding            2         2000         2000

**Congruence**

  cluster  congruence
0       0    0.466252
1       1    0.558377

**Molecular Cluster Score**

,total_score,structure_score,property_score,category_score,separation_score,structure_class_score
0,0.414079,0.647942,0.210152,0.216664,0.485232,0.689688

## euclidean_metrics/acsf_embedding

        embedding  best_k_used  valid_count  total_count
0  acsf_embedding            2         2000         2000

**Congruence**

  cluster  congruence
0       0    0.412655
1       1    0.304355

**Molecular Cluster Score**

,total_score,structure_score,property_score,category_score,separation_score,structure_class_score
0,0.352197,0.611659,0.094033,0.230084,0.333066,0.711498

## euclidean_metrics/chemprop_embedding

            embedding  best_k_used  valid_count  total_count
0  chemprop_embedding            2         2000         2000

**Congruence**

  cluster  congruence
0       0    0.475078
1       1    0.666667

**Molecular Cluster Score**

,total_score,structure_score,property_score,category_score,separation_score,structure_class_score
0,0.566221,0.911941,0.009075,0.608054,0.771108,0.846423

## euclidean_metrics/morgan_fingerprint

            embedding  best_k_used  valid_count  total_count
0  morgan_fingerprint            2         2000         2000

**Congruence**

  cluster  congruence
0       0    0.273152
1       1    0.666667

**Molecular Cluster Score**

,total_score,structure_score,property_score,category_score,separation_score,structure_class_score
0,0.376822,0.550839,0.008817,0.608054,0.3223,0.846423

## euclidean_metrics/selfies_transformer

             embedding  best_k_used  valid_count  total_count
0  selfies_transformer            2         2000         2000

**Congruence**

  cluster  congruence
0       0    0.452477
1       1    0.666667

**Molecular Cluster Score**

,total_score,structure_score,property_score,category_score,separation_score,structure_class_score
0,0.520751,0.8233,0.001619,0.608054,0.693347,0.846423

## euclidean_metrics/soap_embedding

        embedding  best_k_used  valid_count  total_count
0  soap_embedding            2         2000         2000

**Congruence**

  cluster  congruence
0       0    0.471105
1       1    0.552528

**Molecular Cluster Score**

,total_score,structure_score,property_score,category_score,separation_score,structure_class_score
0,0.396638,0.669469,0.157224,0.226255,0.364322,0.671632

## isomers/acsf_embedding_formula_C7H10O2

        embedding  best_k_used  valid_count  total_count
0  acsf_embedding            2          103          103

**Congruence**

  cluster  congruence
0       0     0.60749
1       1     0.49669

**Molecular Cluster Score**

,total_score,structure_score,property_score,category_score,separation_score,structure_class_score
0,0.43615,0.729106,0.077211,0.320419,0.572606,0.814815

## isomers/chemprop_embedding_formula_C7H10O2

            embedding  best_k_used  valid_count  total_count
0  chemprop_embedding            2          103          103

**Congruence**

  cluster  congruence
0       0    0.722646
1       1    0.546717

**Molecular Cluster Score**

,total_score,structure_score,property_score,category_score,separation_score,structure_class_score
0,0.420734,0.725899,0.043576,0.352642,0.467732,0.90566

## isomers/coulomb_matrix_formula_C7H10O2

        embedding  best_k_used  valid_count  total_count
0  coulomb_matrix            5          103          103

**Congruence**

  cluster  congruence
0       0    0.674242
1       1    0.649708
2       2    0.731889
3       3    0.542175
4       4    0.632448

**Molecular Cluster Score**

,total_score,structure_score,property_score,category_score,separation_score,structure_class_score
0,0.388462,0.588862,0.144268,0.404054,0.288256,0.881139

## isomers/morgan_fingerprint_formula_C7H10O2

            embedding  best_k_used  valid_count  total_count
0  morgan_fingerprint            6          103          103

**Congruence**

  cluster  congruence
0       0    0.480824
1       1    0.492029
2       2    0.568985
3       3    0.792719
4       4    0.709034
5       5    0.430490

**Molecular Cluster Score**

,total_score,structure_score,property_score,category_score,separation_score,structure_class_score
0,0.500092,0.524952,0.525049,0.553552,0.218866,0.916667

## isomers/selfies_onehot_formula_C7H10O2

        embedding  best_k_used  valid_count  total_count
0  selfies_onehot            2          103          103

**Congruence**

  cluster  congruence
0       0    0.546062
1       1    0.511766

**Molecular Cluster Score**

,total_score,structure_score,property_score,category_score,separation_score,structure_class_score
0,0.348031,0.560305,0.064618,0.411284,0.222671,0.893617

## isomers/selfies_transformer_formula_C7H10O2

             embedding  best_k_used  valid_count  total_count
0  selfies_transformer            2          103          103

**Congruence**

  cluster  congruence
0       0    0.714143
1       1    0.554842

**Molecular Cluster Score**

,total_score,structure_score,property_score,category_score,separation_score,structure_class_score
0,0.390875,0.674335,0.042431,0.355114,0.37389,0.909091

## isomers/soap_embedding_formula_C7H10O2

        embedding  best_k_used  valid_count  total_count
0  soap_embedding            2          103          103

**Congruence**

  cluster  congruence
0       0    0.622745
1       1    0.531686

**Molecular Cluster Score**

,total_score,structure_score,property_score,category_score,separation_score,structure_class_score
0,0.425691,0.716458,0.082127,0.33587,0.472952,0.880952

## non_euclidean/affine_riemann

            embedding  best_k_used  valid_count  total_count
0  affine_riemann_mds            5         2000         2000

**Congruence**

  cluster  congruence
0       0    0.622007
1       1    0.371435
2       2    0.513919
3       3    0.492960
4       4    0.488825

**Molecular Cluster Score**

,total_score,structure_score,property_score,category_score,separation_score,structure_class_score
0,0.36901,0.61116,0,0.291853,0.661751,0.708007

## non_euclidean/euclidean_riemann

               embedding  best_k_used  valid_count  total_count
0  euclidean_riemann_mds            4         2000         2000

**Congruence**

  cluster  congruence
0       0    0.447072
1       1    0.630996
2       2    0.509046
3       3    0.425936

**Molecular Cluster Score**

,total_score,structure_score,property_score,category_score,separation_score,structure_class_score
0,0.356617,0.580179,0,0.28647,0.672516,0.727839

## non_euclidean/grassmann

       embedding  best_k_used  valid_count  total_count
0  grassmann_mds            2         2000         2000

**Congruence**

  cluster  congruence
0       0    0.427874
1       1    0.401543

**Molecular Cluster Score**

,total_score,structure_score,property_score,category_score,separation_score,structure_class_score
0,0.446,0.87783,0,0.217131,0.514423,0.695647

## non_euclidean/wasserstein

         embedding  best_k_used  valid_count  total_count
0  wasserstein_mds            2         2000         2000

**Congruence**

  cluster  congruence
0       0    0.260263
1       1    0.260604

**Molecular Cluster Score**

,total_score,structure_score,property_score,category_score,separation_score,structure_class_score
0,0.331958,0.623991,0.01886,0.216161,0.334712,0.70595

In [5]:
def plot_all_categories(report_data, categories=None):
    rows = []
    metrics = ['structure_score', 'property_score', 'category_score', 'separation_score', 'structure_class_score']
    
    for key, payload in report_data.items():
        if '/' not in key:
            continue
            
        parts = key.split('/')
        if len(parts) < 2:
            continue
            
        category = parts[0]
        method = parts[1].replace('_cluster_scores.json', '')

        # Filter categories if provided
        if categories is not None and category not in categories:
            continue

        mcs = payload.get("molecular_cluster_score", {})
        
        if isinstance(mcs, dict) and all(m in mcs for m in metrics):
            row = {"category": category, "method": method}
            for m in metrics:
                row[m] = mcs.get(m, 0)
            rows.append(row)

    if not rows:
        print("No valid cluster scores found for the selected categories.")
        return

    df = pd.DataFrame(rows)

    # If categories not provided, infer from dataframe
    if categories is None:
        categories = df['category'].unique()
    else:
        categories = [c for c in categories if c in df['category'].unique()]

    fig = make_subplots(
        rows=len(categories), cols=1,
        specs=[[{'type': 'polar'}] for _ in categories],
        subplot_titles=[f"Category: {c}" for c in categories],
        vertical_spacing=0.05
    )

    colors = ['#636EFA', '#EF553B', '#00CC96', '#AB63FA', '#FFA15A',
              '#19D3AF', '#FF6692', '#B6E880']

    for i, cat in enumerate(categories):
        cat_df = df[df['category'] == cat]

        for j, (_, row) in enumerate(cat_df.iterrows()):
            values = [row[m] for m in metrics]
            values.append(values[0])

            fig.add_trace(
                go.Scatterpolar(
                    r=values,
                    theta=metrics + [metrics[0]],
                    name=row['method'],
                    legendgroup=cat,
                    line=dict(color=colors[j % len(colors)])
                ),
                row=i+1, col=1
            )

    fig.update_layout(
        height=500 * len(categories),
        template="plotly_dark",
        showlegend=True,
        margin=dict(t=100, b=50, l=100, r=100),
        legend=dict(groupclick="toggleitem")
    )
    
    fig.update_polars(radialaxis=dict(visible=True, range=[0, 1]))
    fig.show()

In [6]:
plot_all_categories(report_data, categories=['isomers', 'isomers_euclidean'])

In [7]:
plot_all_categories(report_data, categories=['descriptors_kmeans', 'euclidean_metrics'])

In [8]:
plot_all_categories(report_data, categories = ['non_euclidean', 'isomers_non_euclidean'])